server:
  port: 8081

spring:
  application:
    name: cloud-account

# 服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.139.126:8848
        username: nacos
        password: nacos
      config:
        server-addr: 47.99.139.126:8848
        username: nacos
        password: nacos
        file-extension: properties

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.139.126:3306/cloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Root0000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sms:
  app-code: 5fbfb49511d44247a62f974f37e8e03d
  template-id: JM1000372